// <auto-generated />
using System;
using HotelProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240413190447_rooms")]
    partial class rooms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelProject.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tbilisi",
                            Country = "Georgia",
                            HotelName = "Radisson Blu",
                            PhysicalAddress = "Rose Revolution Square",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            City = "Tbilisi",
                            Country = "Georgia",
                            HotelName = "The Biltmore",
                            PhysicalAddress = "Shota Rustaveli Ave",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            City = "Tbilisi",
                            Country = "Georgia",
                            HotelName = "Rooms Hotel",
                            PhysicalAddress = "Merab Kostava Street",
                            Rating = 4.2999999999999998
                        });
                });

            modelBuilder.Entity("HotelProject.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HotelId")
                        .HasColumnType("int");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId")
                        .IsUnique()
                        .HasFilter("[HotelId] IS NOT NULL");

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Giorgi",
                            HotelId = 1,
                            SecondName = "Gujarelidze"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Saba",
                            HotelId = 2,
                            SecondName = "Gujarelidze"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Irakli",
                            HotelId = 3,
                            SecondName = "Gujarelidze"
                        });
                });

            modelBuilder.Entity("HotelProject.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HotelId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<bool?>("IsBooked")
                        .IsRequired()
                        .HasColumnType("bit");

                    b.Property<double?>("PriceGel")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelId = 1,
                            IsBooked = true,
                            PriceGel = 125.0,
                            RoomName = "Room 1"
                        },
                        new
                        {
                            Id = 2,
                            HotelId = 1,
                            IsBooked = false,
                            PriceGel = 79.989999999999995,
                            RoomName = "Room 2"
                        },
                        new
                        {
                            Id = 3,
                            HotelId = 2,
                            IsBooked = true,
                            PriceGel = 119.98999999999999,
                            RoomName = "Room 1"
                        },
                        new
                        {
                            Id = 4,
                            HotelId = 2,
                            IsBooked = true,
                            PriceGel = 150.0,
                            RoomName = "Room 2"
                        },
                        new
                        {
                            Id = 5,
                            HotelId = 3,
                            IsBooked = false,
                            PriceGel = 122.0,
                            RoomName = "Room 1"
                        });
                });

            modelBuilder.Entity("HotelProject.Models.Manager", b =>
                {
                    b.HasOne("HotelProject.Models.Hotel", "Hotel")
                        .WithOne("Manager")
                        .HasForeignKey("HotelProject.Models.Manager", "HotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelProject.Models.Room", b =>
                {
                    b.HasOne("HotelProject.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("HotelProject.Models.Hotel", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
